### ISSUE TITLE
go get golang.org/x/image 无法获取

### ISSUE THREAD

**Issue by igo9go** [lifei6671/gocaptcha#5]
package golang.org/x/image: unrecognized import path "golang.org/x/image" (https fetch: Get https://golang.org/x/image?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by lifei6671** [comment]
这是golang的官方库，请自备梯子。

**Comment by Zyx-A** [comment]
try to setup a proxy, it worked for me.

export GOPROXY=https://goproxy.io
