### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by phper08** [lifei6671/gocaptcha#6]
https://github.com/lifei6671/gocaptcha/commit/c467a25bc100109308834fc8aa96f7a6123ba6b8#diff-80924c2e51d094cf70dd1a89bf530c18
80行定义
func NewCaptchaImage(width int, height int, bgColor color.RGBA) *CaptchaImage {

https://github.com/lifei6671/mindoc/blob/master/controllers/AccountController.go
446行调用
captchaImage.DrawNoise(gocaptcha.CaptchaComplexLower)

**Comment by lifei6671** [comment]
请使用0.1版本
